# Generated by Django 3.0.4 on 2020-03-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enum', models.IntegerField()),
                ('ename', models.CharField(max_length=60)),
                ('ephone', models.IntegerField()),
            ],
        ),
    ]
