# Generated by Django 3.0.4 on 2020-03-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comapnyname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sel', models.CharField(choices=[('google', 'google'), ('microsoft', 'microsoft')], max_length=600)),
            ],
        ),
    ]
