# Generated by Django 3.0.4 on 2020-03-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20200324_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Tag',
        ),
        migrations.AddField(
            model_name='product',
            name='Tag',
            field=models.ManyToManyField(to='application.Tag'),
        ),
    ]
